### ISSUE TITLE
Erro while building for iOS

### ISSUE THREAD

**Issue by brunoribei-ro** [pragmaflowinc/adalo-geolocation#1]
Hello, So first of all, thank you for building this component. It's really useful and will be a game-changer for the app I am about to launch.
So I got this error while building for iOS:

It may be some issue with the path to the installation script? 

---------> INSTALLING adalo-geo-location
ADDING adalo-geo-location@1.0.0
----------> ./scripts/install_ios.sh [
  'logo',
  'displayName',
  'components',
  'iosInstallScript',
  'androidInstallScript'
]
BEFORE: Stats {
  dev: 16777220,
  mode: 33188,
  nlink: 1,
  uid: 501,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 201155701,
  size: 259,
  blocks: 8,
  atimeMs: 1630962686584.5442,
  mtimeMs: 1630962675773.999,
  ctimeMs: 1630962686074.8994,
  birthtimeMs: 1630962675773.999,
  atime: 2021-09-06T21:11:26.585Z,
  mtime: 2021-09-06T21:11:15.774Z,
  ctime: 2021-09-06T21:11:26.075Z,
  birthtime: 2021-09-06T21:11:15.774Z
}
Error: Command failed: /Users/administrator/Code/TestApp2/node_modules/adalo-geo-location/scripts/install_ios.sh
/bin/sh: /Users/administrator/Code/TestApp2/node_modules/adalo-geo-location/scripts/install_ios.sh: Permission denied

    at ChildProcess.exithandler (child_process.js:390:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 126,
  signal: null,
  cmd: '/Users/administrator/Code/TestApp2/node_modules/adalo-geo-location/scripts/install_ios.sh',
  stdout: '',
  stderr: '/bin/sh: /Users/administrator/Code/TestApp2/node_modules/adalo-geo-location/scripts/install_ios.sh: Permission denied\n'
}

<img width="1441" alt="Screen Shot 2021-09-07 at 02 22 50" src="https://user-images.githubusercontent.com/44805135/132288664-80ed7e20-5693-4aca-8561-f9b202f38815.png">
<img width="1438" alt="Screen Shot 2021-09-07 at 02 23 05" src="https://user-images.githubusercontent.com/44805135/132288680-6663676b-ec83-46d8-8680-9031840b0f26.png">

**Comment by njimmy10** [comment]
hello, I'd like to know if you have solved that issue yet or no?

**Comment by PragmaFlow** [comment]
I think this is close. Sorry I was AWOL for the last month.
