### ISSUE TITLE
Linking from the list does not work

### ISSUE THREAD

**Issue by basilebru** [pragmaflowinc/adalo-geolocation#15]
I've added an action to link to another page when clicking on an item of the list
Yet it does not seem to work

**Comment by PragmaFlow** [comment]
Thanks for the report @Grim22. I will have a look at it. Can you send me a screenshot of what the action looks like. Is it the child/linked data that is causing the issue, or is it simply navigation?

**Comment by basilebru** [comment]
Thanks for your answer.
Here is a screenshot
![image](https://user-images.githubusercontent.com/56433783/143486000-0274a97d-6f99-41d0-ae95-2bef987c2785.png)
It's just a link to another page, on click.
The 'child' page is not the issue, as linking to this page from a regular list works. 
So navigation may be the issue: clicking has no effect.

**Comment by PragmaFlow** [comment]
Found the mistake, thanks for the report. It is fixed now. Please test again and let me know!

**Comment by basilebru** [comment]
It's all good, thanks a lot :)
