### ISSUE TITLE
Two GeoFilteredList

### ISSUE THREAD

**Issue by FabioCappelli-94** [pragmaflowinc/adalo-geolocation#4]
Hi,
Your work would be very usefull but when i want to test with npx adalo dev the components that i see in adalo are two GeoFilteredList.
Unfortunately I need more the GeoLocalization component.
It happened to others?

**Comment by PragmaFlow** [comment]
Yes, It has happened to one other person. We release an installer over the weekend. The suggested installation method is via https://adalo.pragmaflowservers.com/install-component

unless you want to customize the code. If that is the case, I believe it was solved by reordering the components in package.json

swap lines 18-21 with lines 22-25 and fix the comma, should do the trick
