### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by njimmy10** [pragmaflowinc/adalo-geolocation#5]
Error while building
<img width="1440" alt="Screen Shot 2021-10-30 at 1 35 33 AM" src="https://user-images.githubusercontent.com/90354662/139508410-eae6afe9-c052-4d4b-bc3f-d80c2b105fb8.png">

**Comment by khalidousingle** [comment]
hi, i have the same problem, did you find a solution ?

**Comment by njimmy10** [comment]
Hello, visit https://adalo.pragmaflowservers.com/ and download it from there, it works fine.

**Comment by khalidousingle** [comment]
i'll do thank you very much
