### ISSUE TITLE
GeoFilteredList showing error in execution

### ISSUE THREAD

**Issue by MTS2313** [pragmaflowinc/adalo-geolocation#6]
hello your GeoFilteredList component has a runtime error it returns a white screen at runtime even before making the request

**Comment by basilebru** [comment]
I'm facing the same issue.
Here's a screenshot of the console: 
![image](https://user-images.githubusercontent.com/56433783/140796104-4b640e99-647b-4395-8e3a-abf98ceff427.png)

**Comment by PragmaFlow** [comment]
Yes, we have had some reports of issues. We are investigating them now and will create a PR soon. We also created a site for installation here: https://adalo.pragmaflowservers.com/install-component

If you install it via the page, when we release fixes it will automatically be included in your app on the next build. Keep in mind this can cause breaking changes

**Comment by PragmaFlow** [comment]
I believe https://github.com/pragmaflowinc/adalo-geolocation/pull/7 will resolve the issue. I will deploy it now
